name: "Build"

run-name: "Build ${{ github.ref_name }}"

on:
  workflow_dispatch:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]


jobs:
  build:
    name: Build

    env:
      AWS_ACCESS_KEY_ID: dummy-access-key
      AWS_DEFAULT_REGION: us-east-1
      AWS_SECRET_ACCESS_KEY: dummy-access-key-secret

    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.6", "3.9", "3.11" ]

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run:
          make install
      - name: Run tests
        run:
          make test
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        with:
          directory: ./_build/coverage
