name: "CI/CD"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    name: Build

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ 3.6, 3.7, 3.8, 3.9 ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          make install
      - name: Run tests
        run: |
          make test
        shell: bash
      - name: Upload coverage
        if: matrix.python-version == '3.9'
        uses: codecov/codecov-action@v1
        with:
          directory: ./_build/coverage
